#Updated Properties
#Thu Jul 03 14:10:22 IST 2025
APIURl=https\://coverr.io/api/v1/resource/id-3d1969cc?ref\=551&env\=staging
AddTo4=Body
ApiKeyName1=select
AddTo2=Header
AddTo3=Query Params
AddTo1=Select AddTo
key=Koepp_key
AuthType1=Select Auth Type
ApiName=Email Api Key 2
MethodType1=Select Keyfor
MethodType2=SMS
MethodType3=WhatsAPP
MethodType4=Email
MethodType5=WhatsApp Business
MethodType6=Custom
KeyFor1=Select Keyfor
AuthType6=OAuth 2.0
Value=Schaden_value
UserNameBasicAuth=Stark_UN
KeyFor6=Custom
AuthType2=NoAuth
KeyFor5=WhatsApp Business
AuthType3=API Key
KeyFor4=Email
AuthType4=Bearer Token
KeyFor3=WhatsAPP
AuthType5=Basic Auth
KeyFor2=SMS
