#Dropdown Options Extracted with key prefix: AuthType
#Mon Jun 02 15:20:26 IST 2025
AuthType1=Select Auth Type
AuthType6=OAuth 2.0
AuthType2=NoAuth
AuthType3=API Key
AuthType4=Bearer Token
AuthType5=Basic Auth
