#Updated Properties
#Mon Jun 30 16:02:50 IST 2025
APIURl=https\://api.coverr.co/video/id-0b4a5598?ref\=466&env\=staging
ApiKeyName1=select
key=Zulauf_key
AuthType1=Select Auth Type
ApiName=Auer
MethodType1=Select Keyfor
MethodType2=SMS
MethodType3=WhatsAPP
MethodType4=Email
MethodType5=WhatsApp Business
MethodType6=Custom
KeyFor1=Select Keyfor
AuthType6=OAuth 2.0
Value=Hudson_value
UserNameBasicAuth=Stark_UN
KeyFor6=Custom
AuthType2=NoAuth
KeyFor5=WhatsApp Business
AuthType3=API Key
KeyFor4=Email
AuthType4=Bearer Token
KeyFor3=WhatsAPP
AuthType5=Basic Auth
KeyFor2=SMS
