#Updated by extractAllAndStore()
#Thu Jun 12 15:35:11 IST 2025
SearchStage39=DemoK Stage
FormName_data39=broadcast_template
SearchStage36=DemoI Stage
SearchStage35=Ticket Booking _Stage 2
SearchStage38=Hotel_Booking_Stage
SearchStage37=Account_Verification_Stage_3
SearchStage32=Banking_Feedback_Stages
SearchStage31=Not Qualified
SearchStage34=DemoG Stage
SearchStage33=DemoF Stage
SearchStage9=Closed
SearchStage8=In Progress
SearchStage30=Lost Leads
SearchStage7=Resolved
SearchStage6=L1 Review
FormName_data41=dataset_filter
FormName_data40=accessories
SearchStage29=No Answer
SearchStage28=Booking
SearchStage25=Sales Follow Up
SearchStage24=CRC Leads
SearchStage27=Test Drive
SearchStage26=Appointment
SearchStage21=MI Fresh Data
SearchStage20=L4 Escalation
SearchStage23=Fresh Enquries
SearchStage22=MI Call Back
SearchStage5=Not Interested
SearchStage4=Non Contact
SearchStage3=Follow-up
SearchStage2=Fresh Lead
SearchStage1=Search Stage
SearchStage18=L2 Escalation
SearchStage17=L1 Escalation
FormName_data19=audit_the_auditor
FormName_data18=edit_escalated_form
SearchStage19=L3 Escalation
FormName_data17=open_escalated_form
SearchStage14=Follow Up Desk Pending
SearchStage13=Follow Up Desk
SearchStage16=Appointment Desk Pending
SearchStage15=Appointment Desk
SearchStage10=Transfer
SearchStage12=PBF Call Back
SearchStage11=PBF Fresh Data
FormName_data23=whatsapp_template
FormName_data22=sms_template
FormName_data21=email_template
FormName_data20=skip_reason
FormName_data27=rejected_audit_form
FormName_data26=normal_report
FormName_data25=transmon_report
FormName_data24=sample_status
FormName_data29=api_key_setup
FormName_data28=user_status
FormName_data30=menu_setup
FormName_data34=system_name
FormName_data33=transaction_report
FormName_data32=notification
FormName_data31=masters
FormName_data38=dashboards
FormName_data37=user_status_history
FormName_data36=document_name
FormName_data35=site_setup
FormName_data12=sampling_plan_and_generation
FormName_data11=re_allocation
FormName_data10=auto_allocation
FormName_data16=evaluation_tab_view
FormName_data15=view_modify_evaluation
FormName_data14=add_evaluation
FormName_data13=escalation_metrics
SearchStage54=Customer Requirements_Stage
SearchStage53=DemoP Stage
SearchStage55=Ready To Purchase
SearchStage50=Demo_Question_Set_001_Stage
SearchStage52=Registration_Stage
SearchStage51=Vehicle Details_Stage
FormName_data1=data_setup
FormName_data2=workflow_design
FormName_data3=user_setup
FormName_data4=user_management
FormName_data5=role_and_permissions
FormName_data6=alchemy
FormName_data7=user_mapping
FormName_data8=bias
FormName_data9=manual_allocation
SearchStage47=Event Details Stage
SearchStage46=Wyzmindz_Stage
SearchStage49=Testing Master Form_Stage 1
SearchStage48=Testing Master Form_Stage
SearchStage43=DemoN Stage
SearchStage42=DemoM Stage
SearchStage45=DemoO Stage
SearchStage44=Master-Form-Stage-2
SearchStage41=Master-Form-Stage-1
SearchStage40=DemoL Stage
