#Stored Label Names
<<<<<<< HEAD
#Wed May 21 17:54:59 IST 2025
label_3=WhatApp number
label_2=Mobile Number
label_1=Employee Number
label_0=EmployeeName
=======
#Fri Jun 06 15:51:21 IST 2025
label_0=Manager
label_1=Middle Name
label_2=LinkedIn Profile
label_3=Address
label_4=Blood Type
>>>>>>> 82ba1f32e239094f91c4d8da570f681703a5bfe3
