#Dropdown Options Extracted with key prefix: emailFor
#Thu Jul 10 11:47:33 IST 2025
toMail7=Trans Unique Id
toMail6=Trans Unique Id
ApiKeyName1=select
toMail5=Email_id
toMail4=WhatsApp_Number
ApiKeyName3=EmialApi
toMail3=Mobile_Number
ApiKeyName2=Email Api Key 2
toMail2=Customer_Name
toNumberSource2=From System Names
toMail1=Select
emailFor1=Select
toNumberSource1=From Stage Fields
emailFor2=StageSave
emailFor3=Escalation
emailFor4=Rejection
toNumberSource3=Manual
