#Stored all extracted data with prefix: DefaultNames
#Fri Jun 13 16:44:54 IST 2025
DisplayNames5=Role & Permissions
DisplayNames4=User Management
DisplayNames3=User Setup
DisplayNames2=workflowdesign
DisplayNames1=Data Setup
DisplayNames33=Transaction Report
DisplayNames34=System Names
DefaultNames38=Dashboards
DisplayNames31=Masters
DefaultNames39=Broadcast Template
DisplayNames32=Notification Template
DefaultNames36=Document Names
DefaultNames37=User Status History
DisplayNames30=Menu Setup
DefaultNames34=System Names
DefaultNames35=Site Settings
DefaultNames32=Notification
DefaultNames33=Transaction Report
DefaultNames30=Menu Setup
DisplayNames39=Broadcast Template
DefaultNames31=Masters
DisplayNames37=User Status History
DisplayNames9=Manual Allocation
DisplayNames38=Syntheta
DisplayNames8=Bias
DisplayNames35=Site Settings
DisplayNames7=User Mapping
DisplayNames36=Document Names
DisplayNames6=Alchemy
DisplayNames22=SMS Template
DisplayNames23=Whatsapp Template
DisplayNames20=Skip Reason
DisplayNames21=Email Template
DefaultNames41=Dataset Filter
DisplayNames28=User Status
DisplayNames29=API Key Setup
DisplayNames26=Validation Status Report
DefaultNames40=Accessories
DisplayNames27=Rejected Audit Form
DisplayNames24=Sample Status
DisplayNames25=Transmon Report
FormName14=add_evaluation
FormName15=view_modify_evaluation
FormName12=sampling_plan_and_generation
FormName13=escalation_metrics
FormName18=edit_escalated_form
FormName19=audit_the_auditor
FormName16=evaluation_tab_view
FormName17=open_escalated_form
DefaultNames18=Edit Escalated Form
DefaultNames19=Audit the Auditor
DefaultNames16=Evaluation Tab View
DefaultNames17=Open Escalated Form
DefaultNames14=Add Evaluation
DefaultNames15=View/Modify Evaluation
DefaultNames12=Sampling Plan & Generation
DefaultNames13=Escalation Metrics
DefaultNames10=Auto Allocation
DefaultNames11=Re Allocation
FormName10=auto_allocation
FormName11=re_allocation
DefaultNames9=Manual Allocation
DefaultNames8=Bias
DefaultNames7=User Mapping
DefaultNames29=API Key Setup
DefaultNames27=Rejected Audit Form
DefaultNames28=User Status
DefaultNames25=Transmon Report
DisplayNames40=Accessories
DefaultNames26=Normal Report
DisplayNames41=Discount and Scheme
DefaultNames23=Whatsapp Template
DefaultNames24=Sample Status
DefaultNames2=Workflow Design
DefaultNames21=Email Template
DefaultNames1=Data Setup
DefaultNames22=SMS Template
DefaultNames20=Skip Reason
DefaultNames6=Alchemy
DefaultNames5=Role & Permissions
DefaultNames4=User Management
DefaultNames3=User Setup
FormName36=document_name
FormName37=user_status_history
FormName34=system_name
FormName35=site_setup
FormName38=dashboards
FormName39=broadcast_template
FormName32=notification
FormName33=transaction_report
FormName30=menu_setup
FormName31=masters
FormName25=transmon_report
FormName26=normal_report
FormName23=whatsapp_template
FormName24=sample_status
FormName29=api_key_setup
FormName27=rejected_audit_form
FormName28=user_status
FormName21=email_template
FormName22=sms_template
FormName20=skip_reason
FormName7=user_mapping
DisplayNames11=Re Allocation
FormName8=bias
DisplayNames12=Sampling Plan & Generation
FormName9=manual_allocation
DisplayNames10=Gleason
DisplayNames19=Audit the Auditor
FormName1=data_setup
DisplayNames17=Agency Validation
FormName2=workflow_design
DisplayNames18=Edit Validation Form
FormName3=user_setup
DisplayNames15=View/Modify Agency
FormName4=user_management
DisplayNames16=Call Log Tab View
FormName5=role_and_permissions
DisplayNames13=Escalation Metrics
FormName6=alchemy
DisplayNames14=Call Log Stage View
FormName40=accessories
FormName41=dataset_filter
