#Stored from two text field lists with prefixes
#Mon Jun 09 10:44:15 IST 2025
MenuName3=AppKertz
MenuName2=AppBarto
SiteName=Advaitha
MenuURL1=https\://www.haleyllc.com
MenuName1=AppPacoc
MenuURL3=https\://www.haneandsons.com
MenuURL2=https\://www.hayesinc.com
