#Stored all extracted data with prefix: stageSettingsActions
#Mon Jul 21 12:26:54 IST 2025
stageSettingsActions6=Disposition Mapping
stageSettingsActions7=Question Set Mapping
stageSettingsActions4=Call API Configuration
stageSettingsActions5=Audio Format
stageSettingsActions8=SOP Documents
stageSettingsActions9=Report Fields
stageSettingsActions10=Report Filters
stageSettingsActions2=Stage History Fields
stageSettingsActions14=Assign To Filters
stageSettingsActions3=Evaluation Filter
stageSettingsActions13=Stage Process Fields/Interaction History
stageSettingsActions12=Scheduler Filters
stageSettingsActions1=Evaluation Fields
stageSettingsActions11=Stage to Dataset Mapping
stageSettingsActions18=Meta System Mapping
stageSettingsActions17=Auto Sample Creation
stageSettingsActions16=StageWise Assign to Settings
stageSettingsActions15=Reminder Notifications
stageSettingsActions19=Stage Restriction Settings
