#Updated Properties
#Fri Jun 27 12:52:06 IST 2025
APIURl=https\://coverr.io/api/v1/resource/id-a5fa74d6?ref\=507&env\=staging
AddTo4=Body
Description=Sporer_Description
subSubProcess=Impact Map S S P
StatusNameSearch1=Kirlin_Status
StatusNameSearch2=Legros_Status
StatusNameSearch3=Stiedemann_Status
StatusNameSearch4=Break
AddTo2=Header
AddTo3=Query Params
AddTo1=Select AddTo
StatusNameSearch5=Training
StatusNameSearch6=Meeting
StatusNameSearch7=Active
OAuth2.0=oIJ0xGqBwusqHIo4GiT3
key=Nienow_key
process=Beauty P
AuthType1=Select Auth Type
ApiName=Nader
MethodType1=Select Keyfor
MethodType2=SMS
MethodType3=WhatsAPP
MethodType4=Email
menusToHideMultipleOptions1=Manual Allocation
StatusName=Considine_Status
MethodType5=WhatsApp Business
MethodType6=Custom
KeyFor1=Select Keyfor
subProcess=Impact Map S S P
AuthType6=OAuth 2.0
Value=Ullrich_value
UserNameBasicAuth=Hickle_UN
KeyFor6=Custom
KeyFor5=WhatsApp Business
AuthType2=NoAuth
KeyFor4=Email
AuthType3=API Key
AuthType4=Bearer Token
KeyFor3=WhatsAPP
KeyFor2=SMS
AuthType5=Basic Auth
