#Dropdown Options Extracted with key prefix: menusToHideMultipleOptions
#Tue Jun 17 17:03:26 IST 2025
Description=Sporer_Description
StatusNameSearch5=Training
StatusNameSearch6=Meeting
StatusNameSearch7=Active
StatusNameSearch1=Kirlin_Status
StatusNameSearch2=Legros_Status
StatusName=Considine_Status
menusToHideMultipleOptions1=Manual Allocation
StatusNameSearch3=Stiedemann_Status
StatusNameSearch4=Break
